knp_menu:
    twig: true  # set to false to disable the Twig extension and the TwigRenderer
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Kunstmaan\AdminBundle\Entity\User
    group:
        group_class: Kunstmaan\AdminBundle\Entity\Group
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address:        admin@kunstmaan.be
                sender_name:    admin
            template:   FOSUserBundle:Resetting:email.txt.twig
        form:
            type:               fos_user_resetting
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword]
            
monolog:
    handlers:
        main:
            type: rotating_file
            path: %kernel.logs_dir%/%kernel.environment%.log
            level: debug

parameters:
    security.acl.permission.map.class: Kunstmaan\AdminBundle\Helper\Security\Acl\Permission\PermissionMap