services:
    kunstmaan_admin.consolelogger.subscriber:
        class: 'Kunstmaan\AdminBundle\EventListener\ConsoleExceptionSubscriber'
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }
