KunstmaanAdminBundle_default:
    resource: "@KunstmaanAdminBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /admin  

KunstmaanAdminBundle_modules:
    resource: "@KunstmaanAdminBundle/Controller/ModulesController.php"
    type:     annotation
    prefix:   /admin/modules
        
KunstmaanAdminBundle_settings:
    resource: "@KunstmaanAdminBundle/Controller/SettingsController.php"
    type:     annotation
    prefix:   /admin/settings      
    
###########################
## fos_userbundle routes ##
###########################

fos_user_security_login:
    pattern: /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
        
fos_user_security_logout:
    pattern: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting  
         
