<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kunstmaan\AdminBundle\Entity\AnalyticsDailyOverview;

/**
 * AnalyticsDailyOverviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsDailyOverviewRepository extends EntityRepository
{

    /**
     * Get the daily overview data from the database, creates a new entry if the propertyId doesn't exist yet
     *
     * @return AnalyticsDailyOverview $overview
     */
    public function getOverview()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
          'SELECT c FROM KunstmaanAdminBundle:AnalyticsDailyOverview c'
        );

        $result = $query->getResult();
        if (!$result) {
            $overview = new AnalyticsDailyOverview();
            $em->persist($overview);
            $em->flush();
        } else {
            $overview = $result[0];
        }

        return $overview;
    }
}
