<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnalyticsDayOverviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsDayOverviewRepository extends EntityRepository
{
    public function getOverview($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
          'SELECT c FROM KunstmaanAdminBundle:AnalyticsDayOverview c'
        );

        $result = $query->getResult();
        if (!$result) {
            $overview = new AnalyticsDailyOverview();
            $em->persist($overview);
            $em->flush();
        } else {
            $overview = $result[0];
        }

        return $overview;
    }
}
