<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kunstmaan\AdminBundle\Entity\AnalyticsConfig;

/**
 * AnalyticsConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsConfigRepository extends EntityRepository
{
    /**
     * Get the config from the database, creates a new entry if the config doesn't exist yet
     *
     * @return Config $config
     */
    public function getConfig()
    {
        $em    = $this->getEntityManager();
        $query = $em->createQuery(
          'SELECT c FROM KunstmaanAdminBundle:AnalyticsConfig c'
        );

        $result = $query->getResult();
        if (!$result) {
            $config = new AnalyticsConfig();
            $em->persist($config);
            $em->flush();
        } else {
            $config = $result[0];
        }

        return $config;
    }

    public function saveToken($token) {
        $em    = $this->getEntityManager();
        $config = $this->getConfig();
        $config->setToken($token);
        $em->persist($config);
        $em->flush();
    }

    public function savePropertyId($propertyId) {
        $em    = $this->getEntityManager();
        $config = $this->getConfig();
        $config->setPropertyId($propertyId);
        $em->persist($config);
        $em->flush();
    }

    public function saveAccountId($accountId) {
        $em    = $this->getEntityManager();
        $config = $this->getConfig();
        $config->setAccountId($accountId);
        $em->persist($config);
        $em->flush();
    }
}
