<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Kunstmaan\AdminBundle\Entity\AnalyticsOverview;

/**
 * AnalyticsOverviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsOverviewRepository extends EntityRepository
{
    public function getAll()
    {
        $query = $this->getEntityManager()->createQuery(
          'SELECT c FROM KunstmaanAdminBundle:AnalyticsOverview c'
        );

        return $query->getResult();
    }
}
