<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kunstmaan\AdminBundle\Entity\AnalyticsWeek;

/**
 * AnalyticsWeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsWeekRepository extends EntityRepository
{
    public function getWeekOverview() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
          'SELECT c FROM KunstmaanAdminBundle:AnalyticsWeek c'
        );

        $result = $query->getResult();
        if (!$result) {
            $weekOverview = new AnalyticsWeek();
            $weekOverview->setDate(new \DateTime("now"));
            $em->persist($weekOverview);
            $em->flush();
        } else {
            $weekOverview = $result[0];
        }

        return $weekOverview;
    }
}
