<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kunstmaan\AdminBundle\Entity\AnalyticsProperty;

/**
 * AnalyticsPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsPropertyRepository extends EntityRepository
{
    public function getProperty() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
          'SELECT c FROM KunstmaanAdminBundle:AnalyticsProperty c'
        );

        $result = $query->getResult();
        if (!$result) {
            $property = new AnalyticsProperty();
            $em->persist($property);
            $em->flush();
        } else {
            $property = $result[0];
        }

        return $property;
    }
}
