<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Kunstmaan\AdminBundle\Entity\AnalyticsOverview;

/**
 * AnalyticsOverviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsOverviewRepository extends EntityRepository
{
    /**
     * Get all overviews
     *
     * @return array $results A collection of AnalyticOverview objects
     */
    public function getAll()
    {
        $query = $this->getEntityManager()->createQuery(
          'SELECT c FROM KunstmaanAdminBundle:AnalyticsOverview c'
        );

        return $query->getResult();
    }

    /**
     * Get all overviews
     *
     * @param int $id
     *
     * @return AnalyticOverview $result
     */
    public function getOverview($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('o')
          ->from('KunstmaanAdminBundle:AnalyticsOverview', 'o')
          ->where('o.id = :id')
          ->setParameter('id', $id);

        $results = $qb->getQuery()->getResult();
        if ($results) {
            return $results[0];
        }

        return false;
    }

}
